stages:
    - publish

publish:
    only:
        - tags
    stage: publish
    image: python:3.8
    script:
        - sed -i "s/##_VERSION_##/$CI_COMMIT_TAG/g" "setup.py"
        - sed -i "s/##_VERSION_##/$CI_COMMIT_TAG/g" "sli/__init__.py"
        - python3 -m pip install --upgrade pip
        - python3 -m pip install --user --upgrade setuptools wheel
        - python3 setup.py sdist bdist_wheel
        - python3 -m pip install --user --upgrade twine
        - python3 -m twine upload dist/* -u __token__ -p $PYPI_TOKEN